#a Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.spchain.com:
    container_name: orderer.spchain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/spchain.com/orderers/orderer.spchain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/spchain.com/orderers/orderer.spchain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.spchain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.collector.spchain.com:
    container_name: peer0.collector.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.collector.spchain.com
      - CORE_PEER_ADDRESS=peer0.collector.spchain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.collector.spchain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.collector.spchain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.collector.spchain.com:7051
      - CORE_PEER_LOCALMSPID=CollectorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/collector.spchain.com/peers/peer0.collector.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/collector.spchain.com/peers/peer0.collector.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.collector.spchain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.collector.spchain.com:
    container_name: peer1.collector.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.collector.spchain.com
      - CORE_PEER_ADDRESS=peer1.collector.spchain.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.collector.spchain.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.collector.spchain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.collector.spchain.com:7051
      - CORE_PEER_LOCALMSPID=CollectorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/collector.spchain.com/peers/peer1.collector.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/collector.spchain.com/peers/peer1.collector.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.collector.spchain.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.creator.spchain.com:
    container_name: peer0.creator.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.creator.spchain.com
      - CORE_PEER_ADDRESS=peer0.creator.spchain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.creator.spchain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.creator.spchain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.creator.spchain.com:10051
      - CORE_PEER_LOCALMSPID=CreatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/creator.spchain.com/peers/peer0.creator.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/creator.spchain.com/peers/peer0.creator.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.creator.spchain.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.creator.spchain.com:
    container_name: peer1.creator.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.creator.spchain.com
      - CORE_PEER_ADDRESS=peer1.creator.spchain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.creator.spchain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.creator.spchain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.creator.spchain.com:9051
      - CORE_PEER_LOCALMSPID=CreatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/creator.spchain.com/peers/peer1.creator.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/creator.spchain.com/peers/peer1.creator.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.creator.spchain.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.md.spchain.com:
    container_name: peer0.md.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.md.spchain.com
      - CORE_PEER_ADDRESS=peer0.md.spchain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.md.spchain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.md.spchain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.md.spchain.com:12051
      - CORE_PEER_LOCALMSPID=MdMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/md.spchain.com/peers/peer0.md.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/md.spchain.com/peers/peer0.md.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.md.spchain.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.md.spchain.com:
    container_name: peer1.md.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.md.spchain.com
      - CORE_PEER_ADDRESS=peer1.md.spchain.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.md.spchain.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.md.spchain.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.md.spchain.com:11051
      - CORE_PEER_LOCALMSPID=MdMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/md.spchain.com/peers/peer1.md.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/md.spchain.com/peers/peer1.md.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.md.spchain.com:/var/hyperledger/production
    ports:
      - 12051:12051

  peer0.gallery.spchain.com:
    container_name: peer0.gallery.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.gallery.spchain.com
      - CORE_PEER_ADDRESS=peer0.gallery.spchain.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.gallery.spchain.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gallery.spchain.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gallery.spchain.com:14051
      - CORE_PEER_LOCALMSPID=GalleryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gallery.spchain.com/peers/peer0.gallery.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gallery.spchain.com/peers/peer0.gallery.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gallery.spchain.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer1.gallery.spchain.com:
    container_name: peer1.gallery.spchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.gallery.spchain.com
      - CORE_PEER_ADDRESS=peer1.gallery.spchain.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.gallery.spchain.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gallery.spchain.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gallery.spchain.com:13051
      - CORE_PEER_LOCALMSPID=GalleryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gallery.spchain.com/peers/peer1.gallery.spchain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gallery.spchain.com/peers/peer1.gallery.spchain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.gallery.spchain.com:/var/hyperledger/production
    ports:
      - 14051:14051
